version: '2'

services:

    db:
      container_name: postgres_test
      image: postgres
      environment:
        POSTGRES_USER: user_test
        POSTGRES_PASSWORD: passw
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data/

    nginx:
        container_name: container_nginx_test
        build: ./nginx
        restart: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
        - ./log:/var/log/nginx
        volumes_from:
        - api
        depends_on:
        - api

    api:
        container_name: container_api_test
        build: ./server
        restart: always
        command: uwsgi --emperor uwsgi.ini
        volumes:
        - /uwsgi
        - /tmp
        depends_on:
        - db


volumes:
    api_data:
    pgdata:
