version: '2'

services:

    db:
      container_name: postgres_test
      image: postgres
      environment:
        POSTGRES_USER: testing
        POSTGRES_PASSWORD: test_pass
        POSTGRES_DB: test

      volumes:
        - pgdata:/var/lib/postgresql/data/

    nginx:
        container_name: container_nginx_test
        build: ./nginx
        restart: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
        - ./log:/var/log/nginx
        - /static:/static
        volumes_from:
        - api
        depends_on:
        - api

    api:
        container_name: container_api_test
        build: ./server
        restart: always
        command: bash -c 'python3 manage.py migrate && python3 manage.py collectstatic --noinput && uwsgi --emperor uwsgi.ini'
        volumes:
        - /static:/docker_api/static
        - /tmp
        depends_on:
        - db

volumes:
    api_data:
    pgdata:
