# Generated by Django 2.0 on 2018-06-08 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('delete_employee', 'Can see available tasks'), ('edit_employee', 'Can change the status of tasks'), ('migrate_employee', 'Can remove a task by setting its status as closed')),
            },
        ),
        migrations.AlterModelOptions(
            name='departament',
            options={'verbose_name': 'Департамент', 'verbose_name_plural': 'Департаменты'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='positiondepartament',
            options={'verbose_name': 'Позиция в департаменте', 'verbose_name_plural': 'Позиции в департаменте'},
        ),
        migrations.AddField(
            model_name='employeehr',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Employee'),
        ),
    ]
