# Generated by Django 2.0 on 2018-06-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180608_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeehr',
            name='employee',
        ),
        migrations.DeleteModel(
            name='EmployeeHR',
        ),
    ]
